### ISSUE TITLE
Mac (probably Windows) builds with Qt > 5.10 need "styles'

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadroapp#104]
Qt 5.10 changed the way that interface styles are packaged. In addition to the "platforms" plugin directory, there's also a "styles" directory.

If I compile with Qt 5.10+ on Mac, I normally see this:
<img width="325" alt="Screen Shot 2019-11-17 at 9 01 43 PM" src="https://user-images.githubusercontent.com/41128/69019212-92ff7a80-097d-11ea-853e-ced479364a9c.png">

If I copy the "styles" files "libqmacstyle.dylib" to the Plugins directory for deployment, everything looks okay:
<img width="516" alt="Screen Shot 2019-11-17 at 9 00 53 PM" src="https://user-images.githubusercontent.com/41128/69019247-c04c2880-097d-11ea-9ff2-d7949bcd09a7.png">

I can tell that the DeployQt5.cmake files probably need revision, but I can't even tell where they're called or how to add in the updated files.

Any ideas @cryos ?
(I'd think many other apps have similar problems - most seem to directly use the windeployqt and macdeployqt programs instead.)

**Comment by cryos** [comment]
Fixed in #105
