### ISSUE TITLE
Proper "File" --> "Import" and "Build" menus do not exist

### ISSUE THREAD

**Issue by GenKawamura** [OpenChemistry/avogadroapp#109]
**Avogadro version: (please complete the following information from the About box):**
 - avogadro2-libs-1.90.0-12
 - Qt: 5.9.2

**Desktop version: (please complete the following information):**
 - OS: Linux Scienfitic Linux (compatible with Redhat EL7)
 - Version: 7.6
 - Compiler: gcc-c++-4.8.5-39.el7.x86_64, cmake-2.8.12.2-2.el7.x86_64

**Describe the bug**
"File" -> "Import" on the desktop application shows only "Download by Name". On Mac, it has "Fetch from PDB", "Molecular file" etc.
"Build" menu on the desktop application does not show at all.

**To Reproduce**
1. Open Avogadro2 desktop application
2. Click on 'File' --> 'Import' 
3. See the list

4. No "build" menu.

**Expected behavior**
I expect the menu of "import" and "build"

**Additional context**
I used the official builds of Avogadro2 version 1.90 packages in Redhat EL7. I built also them from source files on my computer. But, the proper menu does not come up. Is there any way to put the menu like Mac? Do we need version 1.93?

![avogadro2-desktop](https://user-images.githubusercontent.com/8331616/74735863-d524aa80-5251-11ea-93c5-66df3c2e230e.jpg)

**Comment by kevinsmia1939** [comment]
Does extensions menu show anything? I have same problem with import and build menu, but my extensions only have periodic table.

**Comment by kevinsmia1939** [comment]
I suspect some of the dependency is not satisfied, but I could not confirm.

**Comment by cryos** [comment]
It looks like the extensions are not being built correctly, running from the command line may have more data. Is this a package, or something you have built yourself?

**Comment by GenKawamura** [comment]
It appeared in 1.93. I built it in CentOS7.

The docker image is available here.
https://github.com/Avogadro2-test/avogadro2-docker

I fixed many dependencies in the SPEC file for RHEL7.

**Comment by kevinsmia1939** [comment]
> It appeared in 1.93. I built it in CentOS7.
> 
> The docker image is available here.
> https://github.com/Avogadro2-test/avogadro2-docker
> 
> I fixed many dependencies in the SPEC file for RHEL7.

What are those missing dependencies?

**Comment by GenKawamura** [comment]
The main cause was these packages in RHEL7.

https://github.com/Avogadro2-test/avogadro2-docker/tree/master/avogadro2-packages
libarchive
mmtf-cpp
msgpack

The version dependency of libarchive was very critical in my case. I needed libarchive v3.4.

**Comment by ghutchis** [comment]
@GenKawamura - I take that this is fixed now? I'm going to bump the libarchive version now.

**Comment by ghutchis** [comment]
If you can point me at the .spec file,  I'd like to build RPMs with upcoming releases, thanks.

**Comment by ghutchis** [comment]
Closing since this seems to be fixed. Please submit a new issue if needed.
