### ISSUE TITLE
Port avogadro to python3

### ISSUE THREAD

**Issue by jakobjakobson13** [OpenChemistry/avogadroapp#121]
Avogadro still needs python2 for its compilation even though it is not supported anymore. So, porting of avogadro to python3 should be done soon.

**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.93.0
 - Qt: 5.14

**Comment by ghutchis** [comment]
Where? I'm looking at `HEAD` right now and only see:

```
if(USE_PYTHON)
  find_package(PythonInterp 3 REQUIRED)
  find_package(PythonLibs 3 REQUIRED)
```

**Comment by cryos** [comment]
This is also a surprise to me, can you point out what you mean/where you see a Python 2 dependency. I am not aware of any need for Python in compilation, but it is possible I have forgotten something.

**Comment by jakobjakobson13** [comment]
Yes, sorry that was my fault. I got that completely wrong.
