### ISSUE TITLE
Couldn't compile from source due to a small error in projects.cmake

### ISSUE THREAD

**Issue by esmuigors** [OpenChemistry/avogadroapp#127]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.90.0)
 - Qt: (5.11.3)

**Desktop version: (please complete the following information):**
 - OS: Debian GNU/Linux 10
 - Version (of kernel: 4.19.0-13-amd64, if that is relevant)
 - Compiler: GCC 8.3.0-6

**Describe the bug**
Could not compile the latest version because of a (copy/paste?) error in cmake/projects.cmake: line 36 was:

   set(openbabel_version "openbabel-3-1-1")

instead of:

 set(openbabel_version "3-1-1")

. When I make this correction, everything works well, and Avogadro is compiled (and runs flawlessly).

**Comment by esmuigors** [comment]
oops, sent by accident, will proceed in half of an hour

**Comment by esmuigors** [comment]
Done editing, please consider the issue. And thank You very much for the awesome software!

**Comment by esmuigors** [comment]
The program just tried to download the openbabel binaries from:

'https://github.com/openbabel/openbabel/archive/openbabel-openbabel-3-1-1.tar.gz'

instead of the actual:

'https://github.com/openbabel/openbabel/archive/openbabel-3-1-1.tar.gz'

I corrected the local file in a way to make the structure of openbabel paragraph similar to analogous ones.

**Comment by ghutchis** [comment]
Thanks - this was an intermittent problem. I'm closing for now.
