### ISSUE TITLE
avagadro2 installed from source but only opens window

### ISSUE THREAD

**Issue by recohen** [OpenChemistry/avogadroapp#128]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (e.g. 1.90.0-316-g6d14770)
 - Qt: (e.g., 5.9.5)

**Desktop version: (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. 10.12.4]
 - Compiler (if you built from source)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by recohen** [comment]
Gives the following errors below. cclib is installed and imports fine from python. I do not know what the script is calling wrong python2 either, and why python2. Aboutr does not open a window, and nothing else does either. I just get the main window. I believe everything is up to date. Linux. Centos 3.10.0-1160.6.1.el7.x86_64 Intel 2018 compilers.



base) rcohen@tomcat:~/avogadro2/avogadroapp-1.91.0/build$ avogadro2
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py" ; "Error running script '/usr/bin/python2 /home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py\", line 22, in <module>\n    from cclib.io.ccio import ccopen\nImportError: No module named cclib.io.ccio\n"
libpng warning: Unknown iTXt compression type or method
libpng warning: Unknown iTXt compression type or method
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction

**Comment by recohen** [comment]
I rebuild with gnu and now it opens and seems to run, but with the following errors:
~/avogadro2/avogadroapp-1.91.0/buildgnu$ avogadro2
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py" ; "Error running script '/usr/bin/python2 /home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/rcohen/lib64/avogadro2/scripts/formatScripts/cclibScript.py\", line 22, in <module>\n    from cclib.io.ccio import ccopen\nImportError: No module named cclib.io.ccio\n"
libpng warning: Unknown iTXt compression type or method
libpng warning: Unknown iTXt compression type or method

**Comment by ghutchis** [comment]
That's not a problem.
