### ISSUE TITLE
Installation Error: undefined reference to `blake2sp_init'

### ISSUE THREAD

**Issue by gmseabra** [OpenChemistry/avogadroapp#144]
Hi, I'm trying to install OpenChemistry on RHEL 8.0, basically because I want Avogadro2. I'm following the installation instructions from the [openchemistry_build](https://wiki.openchemistry.org/Build). However, close to the end of the installation, it stops with the message below. Would you be able to tell me what I'm missing?

Thanks a lot!
```
$ cmake --build . --config Release
[...]
[ 97%] Building C object tar/CMakeFiles/bsdtar.dir/__/libarchive_fe/passphrase.c.o
[ 98%] Linking C executable ../bin/bsdtar
../libarchive/libarchive.a(archive_read_support_format_rar5.c.o): In function `reset_file_context':
/home/seabra/work/source/repos/openchemistry/openchemistry-build/thirdparty/libarchive-src/libarchive/archive_read_support_format_rar5.c:853: undefined reference to `blake2sp_init'
../libarchive/libarchive.a(archive_read_support_format_rar5.c.o): In function `update_crc':
/home/seabra/work/source/repos/openchemistry/openchemistry-build/thirdparty/libarchive-src/libarchive/archive_read_support_format_rar5.c:2353: undefined reference to `blake2sp_update'
../libarchive/libarchive.a(archive_read_support_format_rar5.c.o): In function `verify_checksums':
/home/seabra/work/source/repos/openchemistry/openchemistry-build/thirdparty/libarchive-src/libarchive/archive_read_support_format_rar5.c:3870: undefined reference to `blake2sp_final'
collect2: error: ld returned 1 exit status
gmake[5]: *** [tar/CMakeFiles/bsdtar.dir/build.make:224: bin/bsdtar] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:1173: tar/CMakeFiles/bsdtar.dir/all] Error 2
gmake[3]: *** [Makefile:141: all] Error 2
gmake[2]: *** [thirdparty/CMakeFiles/libarchive.dir/build.make:114: thirdparty/libarchive-prefix/src/libarchive-stamp/libarchive-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:367: thirdparty/CMakeFiles/libarchive.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
```

**Comment by ghutchis** [comment]
(never mind, just realized  that fix didn't make it into `openchemistry` - you  should be able to `git pull origin` in the `openchemistry` repo and get the patch.)

**Comment by ghutchis** [comment]
Please let me know  if you're able to build now so that I can close the  issue.  Thank!

**Comment by gmseabra** [comment]
Thanks,

Now the install went a lot further, However, it stopped again with a different error. When it tries to download GLEW, it crashes because the file apparently does not exist:

```
[...]
Scanning dependencies of target glew
[ 51%] Creating directories for 'glew'
[ 52%] Performing download step (download, verify and extract) for 'glew'
-- Downloading...
   dst='/home/seabra/Downloads/glew-2.2.0.tgz'
   timeout='none'
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
-- Retrying...
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz'
CMake Error at glew-prefix/src/glew-stamp/download-glew.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/nigels-com/glew/archive/glew-2.2.0.tgz' failed
         status_code: 22
         status_string: "HTTP response code said error"
[...]
gmake[2]: *** [thirdparty/CMakeFiles/glew.dir/build.make:90: thirdparty/glew-prefix/src/glew-stamp/glew-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:441: thirdparty/CMakeFiles/glew.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
```

:-(

All I want there is to install Avogadro2...

**Comment by ghutchis** [comment]
I think this should be fixed in a new `openchemistry` patch now too.

Sorry .. building on other packages makes the development easier, but makes building annoying...

Fingers crossed that it should be working  now.

**Comment by gmseabra** [comment]
You don't have to apologize! You are already providing an incredible service to the community, and I'm the one who should be apologizing for taking your time...

Anyways, I could get a bit further now. But the build still dies in:

```
[...]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SPGLIB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core

-- Configuring incomplete, errors occurred!
See also "/home/seabra/work/source/repos/openchemistry/openchemistry-build/avogadrolibs/CMakeFiles/CMakeOutput.log".
See also "/home/seabra/work/source/repos/openchemistry/openchemistry-build/avogadrolibs/CMakeFiles/CMakeError.log".
gmake[2]: *** [CMakeFiles/avogadrolibs.dir/build.make:114: avogadrolibs-prefix/src/avogadrolibs-stamp/avogadrolibs-configure] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/avogadrolibs.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
```

**Comment by ghutchis** [comment]
When you're in the source directory `openchemistry`:
- `cd avogadroap; git pull origin master`
- `cd avogadrolibs; git pull origin master`

This should get the latest code for everything, which includes a pile of fixes.

We're hopeful that this summer, we'll have a student working on molecular surfaces, ribbon / cartoons.. please continue to submit  feedback, suggestions .. it's always a big help.

**Comment by ghutchis** [comment]
BTW, if we have an `AppImage` or `Flatpak` would that help? I have nightly builds for Mac and  Windows and have been trying to figure out the best option(s) for Linux users.

**Comment by gmseabra** [comment]
> When you're in the source directory `openchemistry`:
> 
> * `cd avogadroap; git pull origin master`
> * `cd avogadrolibs; git pull origin master`
> 
> This should get the latest code for everything, which includes a pile of fixes.
> 
> We're hopeful that this summer, we'll have a student working on molecular surfaces, ribbon / cartoons.. please continue to submit feedback, suggestions .. it's always a big help.

OK, that worked. I could finally compile Avogadro2. Thanks!!

(It is working fine, but it cannot seem to open Gaussian output files. I'll raise a different issue for that. Thanks!)

**Comment by gmseabra** [comment]
> BTW, if we have an `AppImage` or `Flatpak` would that help? I have nightly builds for Mac and Windows and have been trying to figure out the best option(s) for Linux users.

I have never used either, but I noticed I have Flatpak installed locally here. That may be very useful for computers managed by a centralized IT department, as here.
