### ISSUE TITLE
plugins on Avogadro 1.93.0 not recognized

### ISSUE THREAD

**Issue by jape2** [OpenChemistry/avogadroapp#178]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.93.0
 - Qt: 5.12.8

**Desktop version: (please complete the following information):**
 - OS: Ubuntu LTS
 - Version 20.04
 - Compiler - precompiled and installed through Ubuntu Software tool

**Describe the bug**

Trying to install plugins.  They appear to download using the 'Plugin Downloader".  I can see the folder 
~/.local/share/OpenChemistry/Avogadro/ has 'inputGenerators' with the folder 
'OpenChemistry-avogenerators-4672519' which contains the *.py files.  However, the inputgenerator does not appear in the Extension or Quantum menus. 

The same behavior is observed for all the plugins.   They can be downloaded but the application does not recognize they were downloaded.

Thanks,

Jape

**To Reproduce**
1. Go to 'Extensions'
2. Click on '.Plugin Downloader'
3. Select an update
4. go to '~/.local/Avogadro' directory see plugin directory created, but plugins do not work.

**Expected behavior**
Plugins to install after downloaded.

**Comment by ghutchis** [comment]
This has been fixed in Avogadro 1.94, which has been out for over a month:
https://two.avogadro.cc/ 

I believe there are 1.94 packages, but if not, please contact the [debichem team](https://debichem-team.pages.debian.net)

**Comment by xkforce** [comment]
1.94 is still very much downloading scripts into the other directory instead of commands.
