### ISSUE TITLE
Can not buid at Fedora 22

### ISSUE THREAD

**Issue by LonelySpooky** [OpenChemistry/avogadroapp#18]
Using Boost to replace C++11 smart pointers that are not available.
Boost version: 1.57.0
Adding cylinders_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/cylinders_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/cylinders_fs.h cylinders_fs
Adding cylinders_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/cylinders_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/cylinders_vs.h cylinders_vs
Adding linestrip_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/linestrip_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/linestrip_fs.h linestrip_fs
Adding linestrip_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/linestrip_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/linestrip_vs.h linestrip_vs
Adding mesh_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/mesh_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/mesh_fs.h mesh_fs
Adding mesh_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/mesh_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/mesh_vs.h mesh_vs
Adding spheres_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/spheres_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/spheres_fs.h spheres_fs
Adding spheres_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/spheres_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/spheres_vs.h spheres_vs
Adding sphere_ao_depth_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_depth_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_depth_vs.h sphere_ao_depth_vs
Adding sphere_ao_depth_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_depth_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_depth_fs.h sphere_ao_depth_fs
Adding sphere_ao_bake_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_bake_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_bake_vs.h sphere_ao_bake_vs
Adding sphere_ao_bake_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_bake_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_bake_fs.h sphere_ao_bake_fs
Adding sphere_ao_render_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_render_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_render_vs.h sphere_ao_render_vs
Adding sphere_ao_render_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_render_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/sphere_ao_render_fs.h sphere_ao_render_fs
Adding textlabelbase_fs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/textlabelbase_fs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/textlabelbase_fs.h textlabelbase_fs
Adding textlabelbase_vs.glsl to encoder... /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/textlabelbase_vs.glsl /home/henrique/Downloads/avogadrolibs-0.7.2/avogadro/rendering/textlabelbase_vs.h textlabelbase_vs
Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
Using automoc for Qt library
Using automoc for Qt library
CMake Error at avogadro/qtplugins/CMakeLists.txt:98 (add_subdirectory):
  add_subdirectory given source "bonding" which is not an existing directory.

CMake Warning (dev) at avogadro/qtplugins/crystal/CMakeLists.txt:28 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "CrystalScene".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/editor/CMakeLists.txt:24 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "Editor".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/manipulator/CMakeLists.txt:22 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "Manipulator".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/mongochem/CMakeLists.txt:14 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "MongoChem".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
CMake Error at avogadro/qtplugins/CMakeLists.txt:115 (add_subdirectory):
  add_subdirectory given source "playertool" which is not an existing
  directory.

CMake Error at avogadro/qtplugins/CMakeLists.txt:116 (add_subdirectory):
  add_subdirectory given source "povray" which is not an existing directory.

CMake Warning (dev) at avogadro/qtplugins/ballandstick/CMakeLists.txt:9 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "BallStick".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/vanderwaals/CMakeLists.txt:9 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "VanDerWaals".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at avogadro/qtplugins/CMakeLists.txt:129 (add_subdirectory):
  add_subdirectory given source "wireframe" which is not an existing
  directory.

CMake Warning (dev) at avogadro/qtplugins/meshes/CMakeLists.txt:9 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "Meshes".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/overlayaxes/CMakeLists.txt:18 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "OverlayAxes".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at avogadro/qtplugins/vanderwaalsao/CMakeLists.txt:9 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "VanDerWaalsAO".  All uses of target_link_libraries with a
  target should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * avogadro/qtplugins/CMakeLists.txt:78 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

Using automoc for Qt library
Configuring incomplete, errors occurred!
See also "/home/henrique/Downloads/avogadrolibs-0.7.2/CMakeFiles/CMakeOutput.log".
See also "/home/henrique/Downloads/avogadrolibs-0.7.2/CMakeFiles/CMakeError.log".

**Comment by cryos** [comment]
I am just in the process of tagging a new release as this one is quite old at this stage. It looks like directories are missing in the qtplugins level. It will require Qt 5.x, but has many updated features. If this persists I would be happy to investigate further.

**Comment by calewis** [comment]
Just a note for Fedora.  qt5 libraries are not installed with the normal yum install qt.  You have to install the libraries separately using the qt5 prefix.  yum or dnf (I think fedora 22 actually uses dnf) should show you these libraries with yum search qt5.  

Hopefully this was the issue, if not sorry.

**Comment by cryos** [comment]
Closing as I never heard anything back. Qt 5 is a hard dependency, I would be happy to help with any issues building/packaging on Fedora. Please reopen or open a new bug if this issue persists. Thanks!
