### ISSUE TITLE
Building DNA/RNA

### ISSUE THREAD

**Issue by bevsxyz** [OpenChemistry/avogadroapp#186]
**Is your feature request related to a problem? Please describe.**
I had to use the [building DNA/RNA](https://avogadro.cc/docs/building-molecules/building-dna-rna/) feature for a blender workshop. But I could not compile the original Avogadro for Linux because of the outdated dependencies. I am in Arch Linux. The current version of avogadroapp has

- Fragment
- SMILES
- InChl

under build-> insert. I wish the DNA/RNA option also could be implemented, as my alternative just picking up a bDNA structure from pdb wasn't anywhere close to neat.

**Describe the solution you'd like**
I would ideally see it working exactly like in https://avogadro.cc/docs/building-molecules/building-dna-rna/

**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by bevsxyz** [comment]
Found a related issue in the libs repo https://github.com/OpenChemistry/avogadrolibs/issues/230#issue-305391513

**Comment by ghutchis** [comment]
Yes, this would be an issue for `avogadrolibs` - I'm going to close this as a duplicate. Please follow / comment on https://github.com/OpenChemistry/avogadrolibs/issues/230
