### ISSUE TITLE
Error on compilation Arch Linux

### ISSUE THREAD

**Issue by HideyoshiNakazone** [OpenChemistry/avogadroapp#193]
**Avogadro version: 1.95.0
 - Avogadrolibs: Not known
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Arch Linux
 - Version 2021.08.01
 - Compiler 11.1.0

**Describe the bug**
During Compilation the following error is given
``avogadroapp-1.95.0/avogadro/mainwindow.cpp:34:10: fatal error: avogadro/qtgui/layermodel.h: No such file or directory
   34 | #include <avogadro/qtgui/layermodel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.``

**To Reproduce**
1. Compile Avogadroapp 1.95.0 via Qt 5.15.2

**Screenshots**
![image](https://user-images.githubusercontent.com/60374951/129908794-6c9c1784-595b-4a1a-8f63-1494ebc8cc75.png)

**Comment by ghutchis** [comment]
I don't know how Arch packages the source, but you need to compile `avogadroapp` with `avogdrolibs` together: 
http://two.avogadro.cc/build.html

**Comment by HideyoshiNakazone** [comment]
Sorry, it's my mistake, arch's repo still ships the avogadrolibs 1.94.0-1 version, mas that is the origin of my error, thank you very much!

**Comment by ghutchis** [comment]
No worries - thanks for reporting anyway. Hopefully it'll update soon. I flagged the package as out-of-date and asked the package maintainer if there's a good way to keep them aware of new releases.
