### ISSUE TITLE
QtGui directory

### ISSUE THREAD

**Issue by antoscha** [OpenChemistry/avogadroapp#194]
Hi,

I found that at least one file `mainwindow.cpp` requires the presence of `avogadro/qtgui` folder:
```
avogadroapp-1.95.0/avogadro/mainwindow.cpp:34:10: fatal error: avogadro/qtgui/layermodel.h: No such file or directory
   34 | #include <avogadro/qtgui/layermodel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [avogadro/CMakeFiles/avogadro.dir/build.make:163: avogadro/CMakeFiles/avogadro.dir/mainwindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:118: avogadro/CMakeFiles/avogadro.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
Could you please put it in the distribution?

Anton K.

**Comment by ghutchis** [comment]
You need to compile both `avogadroapp` and `avogadrolibs` together - this is why they are released together.
http://two.avogadro.cc/build.html

**Comment by ghutchis** [comment]
Please post on https://discuss.avogadro.cc/ with what you've done and what error you are receiving.
