### ISSUE TITLE
Please consider including an appdata file for Avogadro

### ISSUE THREAD

**Issue by alxpl** [OpenChemistry/avogadroapp#2]
Hello,

GNOME and KDE will soon get their own software centers. There is a requirement for applications to ship an .appdata.xml file, which is to be placed in /usr/share/appdata, just like .desktop files are placed in /usr/share/applications. These files contain a description of each application, links to 16:9 screenshots and other information (e.g. homepage, project license etc.).

You can read about the specifics of AppData here:

people.freedesktop.org/~hughsient/appdata/
http://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

If you do not have the time, I would be more than happy to write one for you; I've been a long time Avogadro user and I would love to give something back. If you decide to prepare your own, please drop me a line, so that I may update the list of compatible applications in Fedora. I would also like to ask you to add that same file to the 1.x branch.

Best Regards

P.S.: I have sent the same message to kitware.com, but I was not sure if that was the appropriate route, so I am opening this issue.

**Comment by cryos** [comment]
I failed to do this, I will try to take a look soon. These files are new to me, but we would of course like to see Avogadro show up on the major Linux distros.

**Comment by alxpl** [comment]
I have some AppData xml files here:
https://alexpl.fedorapeople.org/AppData/
The one for pybliographer contains captions for the screenshots.

The most tricky part was taking screenshots with the right dimensions in DEs other than GNOME, because the reported window size does not take window borders into account.
However, in GNOME you could use the Screenshot Window Sizer extension:
https://extensions.gnome.org/extension/881/screenshot-window-sizer/
With Ctrl+Alt+S and Ctrl+Alt+Shift+S you can cycle between 16:9 window sizes to find the one that looks best before taking the screenshot.

If you need any more help, don't hesitate to ask.

**Comment by hfiguiere** [comment]
there is an appstream file in the `/flatpak/` directory. It's not specific to flatpak at all so all you need is to install it in `$PREFIX/share/metainfo`
