### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by sagitter** [OpenChemistry/avogadroapp#206]
Hi all.

**Avogadro version:**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.2

**Desktop version:**
 - OS: Fedora
 - Version: 34
 - Compiler (if you built from source) GCC-11.2.1

**Describe the bug**
I have compiled Avogadro2 from source and installed the i18n files into the directory `/usr/share/avogadro2/i18n`:
```
/usr/share/avogadro2/i18n
/usr/share/avogadro2/i18n/avogadroapp
/usr/share/avogadro2/i18n/avogadroapp.pot
/usr/share/avogadro2/i18n/avogadroapp/avogadroapp-*.qm
/usr/share/avogadro2/i18n/avogadrolibs/avogadrolibs-*.qm
/usr/share/avogadro2/i18n/*.po
```
How to use these translations? I don't see any option in menu.

**Comment by ghutchis** [comment]
First up, when you start up from the console / terminal, it should tell you what locale / language it expects, e.g.
`Locale:  "en_US"`

At the moment, there is not any UI for switching translations - ideas welcome.

Secondly, the code for loading translations is here: https://github.com/OpenChemistry/avogadroapp/blob/master/avogadro/avogadro.cpp#L66

The fastest workaround is to use the `AVOGADRO_TRANSLATIONS` environment variable.

We can look through a variety of paths - I see that we should have added INSTALL_PREFIX / `/usr/share/` - suggestions / patches are most welcome.

One thing, I'd also like to enable is the **Extensions** => **Download Plugins** (i.e., to a user directory).

**Comment by sagitter** [comment]
Hi @ghutchis 

Why does CMake download both `avogadroapp/*.qm` and `avogadrolibs/*.qm` language files?
Are useful even the *.po files provided into the source archive?

**Comment by ghutchis** [comment]
Because the `avogadroapp` and `avogadrolibs` are separate, they need separate `*.pot` translation templates. The `*.po` files are used by @weblate and allow people to either use the Weblate system or translate directly. (Some people have preferred this historically.) The `*.po` files are also used by other systems (e.g., we imported them from Launchpad, which we used for earlier releases).

The Mac and Windows versions include the `avogadroapp/*.qm` and `avogadrolibs/*.qm` as well as various `qt*.qm` translation files as well. The Qt translation code looks through a few files to see if it finds a string translation.

**Comment by ovari** [comment]
> At the moment, there is not any UI for switching translations - ideas welcome.

Can you copy the idea from [FreeTube](https://freetubeapp.io/)?

Have a drop-down with the first item being `System setting` (with the string being set as the default and also being translatable), then `English (US)` (always written in English as this is your source strings), then the languages in alphabetical order (written in the native language).

* If the computer is restarted in a different local Avogadro2 will show in that locale without user intervention if `System setting` is chosen. This should be the default setting.
* This will mean that you don't need to translate each language in the drop-down box.
* People can find their language as it is written in their native language.
* When the locale in the drop-down is changed, refresh the GUI in that language, with no restart required.

![kép](https://user-images.githubusercontent.com/17465872/132785589-67b3d02b-3f5e-4425-a01b-3ff3c0e035fe.png)

You can look at the FreeTube code at their [GitHub repository](https://github.com/FreeTubeApp/FreeTube).

What do you think?

Thank you

**Comment by sagitter** [comment]
`The fastest workaround is to use the AVOGADRO_TRANSLATIONS environment variable.`

I installed `avogadroapp-it.qm` in `/usr/share/avogadro2/translations/`, so how should i use it to translate avogadro2?

```
$ export AVOGADRO_TRANSLATIONS=/usr/share/avogadro2/translations
$ export LANG=it-IT
$ LD_LIBRARY_PATH=/usr/lib64/avogadro2 avogadro2
```

Thank you.

**Comment by ghutchis** [comment]
I'm guessing from your message that the translations aren't showing up (BTW, `export LANG=it` should be enough.)

I'm trying to figure out what's going on considering this process worked with Avo1 and Qt4:
https://forum.qt.io/topic/130244/help-debugging-translation-failure

**Comment by ovari** [comment]
[Qt 6.2 Release Candidate](https://wiki.qt.io/Qt_6.2_Release) seems to be out. Could upgrading to Qt 6.2 solve the issue?

**Comment by ghutchis** [comment]
Okay @ovari @sagitter - I think #264 should fix loading translations. Finally found the bug. (silly, silly bug).

Maybe @sagitter can tell me if the `avogadroapp` code properly finds the `qtbase` translations on Linux?
