### ISSUE TITLE
Flatpak - opening and windows resizing

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#208]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.3

**Desktop version: (please complete the following information):**
 - OS: Linux Mint
 - Version: 20.2 Cinnamon
 - Compiler: (if you built from source): Not applicable as installed from [Flathub](https://flathub.org/apps/details/org.openchemistry.Avogadro2) using the Linux Mint `Software Manager`

**Describe the bug**
1. When opening it doesn't fill in the application window.
2. When maximizing the window it doesn't fill in the application window.

**Expected behavior**
The app should refresh the window after opening and when it after being resized.

**Screenshots**
Screenshot shows what the Avogadroapp looks like when maximizing the window.
![kép](https://user-images.githubusercontent.com/17465872/132147422-7e62f18c-0ded-4651-b5db-0dd04aa16dd0.png)

**Additional context**
Is the Qt version in Avogadro going to be upgraded to the latest version, i.e. [Qt 6](https://www.qt.io/product/qt6)?

Thank you

**Comment by ghutchis** [comment]
I don't know why that would happen. That seems like either a Qt bug or in your graphics driver / X11 stack.

Please feel free to post in the forum to see if others are having the same problem. The Flatpak maintainer is quite active:
https://discuss.avogadro.cc

As for Qt - we will begin migration to Qt 6.2, but we tend to wait on upgrading until distros have good support. (Also, Qt 6.0 and 6.1 weren't feature-complete.)

**Comment by ovari** [comment]
Don't have an [Avogadro Discussion](https://discuss.avogadro.cc) account.

Looking forward to your Qt 6.2 version; however, we can still test a version before that if a Hungarian version comes out.

Thank you once again.

**Comment by ghutchis** [comment]
BTW, you might want to try the new AppImage build. Not sure if it changes your graphics problem, but it's probably worth a try:
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip

**Comment by ovari** [comment]
> BTW, you might want to try the new AppImage build. Not sure if it changes your graphics problem, but it's probably worth a try:
> https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip

1. Download
2. Extract
3. Set as Executable
4. Click on the file and nothing opens.

**Comment by jsgadas** [comment]
Hi, a similar issue happens here on Elementary 6 with the flatpak version 1.95-1. The Appimage version works well though.

![output](https://user-images.githubusercontent.com/38897885/132775967-15263765-7c95-4137-8549-47aaaf1f3e45.gif)

**Comment by ghutchis** [comment]
I'd ask @kevinsmia1939 - but I don't handle the Flatpak packaging.

**Comment by kevinsmia1939** [comment]
Hi @ovari 

Could you show me what your Flatpak version your distro install?
Using this command will show you the flatpak version.
`flatpak --version`

My version is currently 1.11.3.

I suspect that Linux Mint ship older version of Flatpak.
If your version is older, try to add flatpak repo and update it.

 sudo add-apt-repository ppa:alexlarsson/flatpak
 sudo apt update
 sudo apt install flatpak

And reboot your machine for good measure. Let me know what happen.

**Comment by kevinsmia1939** [comment]
Might or might not relate, but I have issue with nvidia driver 470.63.01, tried downgrade it and see what happen.

**Comment by ovari** [comment]
Hi @kevinsmia1939

Thank you for your response.

> Could you show me what your Flatpak version your distro install?
> Using this command will show you the flatpak version.
> `flatpak --version`

Flatpak 1.6.5

> My version is currently 1.11.3.

So you are correct, it does seem a bit old.

> I suspect that Linux Mint ship older version of Flatpak.
> If your version is older, try to add flatpak repo and update it.
> 
> sudo add-apt-repository ppa:alexlarsson/flatpak
> sudo apt update
> sudo apt install flatpak
> 
> And reboot your machine for good measure. Let me know what happen.

@mtwebster can you please update Linux Mint 20.2 Cinnamon so that everyone has the latest Flatpak version?

> Also, what is your hardware spec?

CPU: Intel© Celeron© N4000 CPU @ 1.10GHz × 2
Graphics card: Intel Corporation UHD Graphics 605
RAM: 3.4 GiB
HDD: 62.5 GB

**Comment by kevinsmia1939** [comment]
@ovari 
Linux mint 20.2 is based on Ubuntu 20.04, which use the old version of flatpak. So they won't update it until they based mint on newer ubuntu.
I suggest you try update flatpak by add the repo.

**Comment by ovari** [comment]
> I suspect that Linux Mint ship older version of Flatpak.
> If your version is older, try to add flatpak repo and update it.
> 
> sudo add-apt-repository ppa:alexlarsson/flatpak
> sudo apt update
> sudo apt install flatpak
> 
> And reboot your machine for good measure. Let me know what happen.

After reboot, the Software Manager has updates.

![kép](https://user-images.githubusercontent.com/17465872/132944910-10748ff7-0642-4c14-8708-04a11344a4ad.png)

So updating... and then run Avogadro2

![kép](https://user-images.githubusercontent.com/17465872/132944981-3b4528dc-7801-4292-a039-ea4fc4d74cac.png)

Avogadro2 doesn't show. It does however distort the Firefox window. Hover mouse above the Avogadro2 app and you see the popup.

**Comment by ovari** [comment]
Moving Avogadro2 to second display and back again shows Avogadro2 correctly.

![kép](https://user-images.githubusercontent.com/17465872/132945068-d3c7a31b-4594-4cee-bf09-2e7f3dec046b.png)

Is there a bug if 2 displays are attached to to computer?

**Comment by kevinsmia1939** [comment]
hmm, not sure.

**Comment by kevinsmia1939** [comment]
Hi, could you try with the new Avogadro 1.96.0, should be publish soon. Try updating with command "flatpak update".

**Comment by ovari** [comment]
Works for me with:

```
Avodagro2
Version: 1.96.0
AvogadroLibs Version: 1.96.0
Qt Version: 5.15.4
```

```
$ flatpak --version
Flatpak 1.12.2
```

Linux Mint 20.3 Cinnamon

Thank you

**Comment by ghutchis** [comment]
Thanks for your help - glad this is fixed now.
