### ISSUE TITLE
Segmentation fault on Arch Linux due to Qt 4 and 5

### ISSUE THREAD

**Issue by berquist** [OpenChemistry/avogadroapp#21]
I'm writing PKGBUILDs for the different OpenChemistry components (MongoChem is still a WIP):

* `molequeue`: https://aur4.archlinux.org/molequeue-git.git/
* `avogadrolibs`: https://aur4.archlinux.org/avogadrolibs-git.git/
* `avogadroapp`: https://aur4.archlinux.org/avogadro2-git.git/

There aren't any issues during compilation, but it segfaults immediately. GDB reveals:
```
(gdb) backtrace 
#0  0x00007fffe764fc34 in ?? () from /usr/lib/libQtGui.so.4
#1  0x00007ffff7dea0ea in call_init.part () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7dea1fb in _dl_init () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7ddbdba in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#4  0x0000000000000001 in ?? ()
#5  0x00007fffffffe42a in ?? ()
#6  0x0000000000000000 in ?? ()
```
It looks like both Qt4 and Qt5 versions of the same library are getting linked in:
```
[eric@osmium]$ ldd avogadro2 | grep -i "qt"
2:	libAvogadroQtOpenGL.so => /usr/lib/libAvogadroQtOpenGL.so (0x00007f7b796a4000)
3:	libAvogadroQtPlugins.so => /usr/lib/libAvogadroQtPlugins.so (0x00007f7b79371000)
7:	libQt5OpenGL.so.5 => /usr/lib/libQt5OpenGL.so.5 (0x00007f7b78ad9000)
8:	libAvogadroQtGui.so => /usr/lib/libAvogadroQtGui.so (0x00007f7b7886a000)
9:	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f7b77fb6000)
10:	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f7b7784a000)
11:	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f7b7715d000)
15:	libQtNetwork.so.4 => /usr/lib/libQtNetwork.so.4 (0x00007f7b766fd000)
23:	libQt5Concurrent.so.5 => /usr/lib/libQt5Concurrent.so.5 (0x00007f7b749a8000)
26:	libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f7b741de000)
28:	libvtkGUISupportQtOpenGL-6.1.so.1 => /usr/lib/libvtkGUISupportQtOpenGL-6.1.so.1 (0x00007f7b73c97000)
56:	libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x00007f7b6e438000)
67:	libvtkGUISupportQt-6.1.so.1 => /usr/lib/libvtkGUISupportQt-6.1.so.1 (0x00007f7b69f72000)
68:	libQtOpenGL.so.4 => /usr/lib/libQtOpenGL.so.4 (0x00007f7b69c6e000)
69:	libQtGui.so.4 => /usr/lib/libQtGui.so.4 (0x00007f7b68f35000)
```

**Comment by cryos** [comment]
That is odd, I develop on Arch Linux, and have not encountered this issue. I would love to see some Arch builds, and will look into it. What versions are you using? They should all be using Qt 5 now - maybe something isn't quite right.

**Comment by berquist** [comment]
I'm using the latest versions from Git for the OpenChemistry packages, and all the supporting libraries are whatever the latest version is from Arch, but *not* development/Git versions. 

* CMake 3.2.3 (3.3.0 is in testing)
* VTK 6.1.0
* Qt 4.8.7
* Qt 5.5.0

**Comment by cryos** [comment]
Ah, you would have to build VTK against Qt 5 - that is likely the issue.

**Comment by berquist** [comment]
Ok, I'll give it a shot and report back.

**Comment by berquist** [comment]
Taking the current Arch build script for VTK and changing the version from 4 -> 5 fixes this; everything works now.

About 1-2 seconds after the main window pops up, a little box with a loading bar that never moves pops up. Closing it doesn't seem to affect anything. Could this be a problem with the build, or is it something else?

![2015-08-01-112532_1920x1200_scrot](https://cloud.githubusercontent.com/assets/727571/9023265/18ba1514-3862-11e5-8a8d-9f7f9f465b36.png)

**Comment by cryos** [comment]
Not sure - never seen that before. I am at a conference this week, with no access to my main development machines running Arch. Can you use the application otherwise? I have tagged a 0.8.0 release and am finalizing the pieces, so it would be great to get packages (and I intend to make more regular releases too).

**Comment by berquist** [comment]
As far as I can tell, everything else is working fine.

**Comment by barrymoo** [comment]
For reference, I see the same box upon opening Avogadro. However, I have not had the Qt issue on any of my Arch machines.

**Comment by cryos** [comment]
I see it now that I am back and compiling on the latest Arch. Not seen it before, will try and track it down. Very irritating, not sure what is popping it up.

**Comment by cryos** [comment]
Pull request #28 (https://github.com/OpenChemistry/avogadrolibs/pull/28) fixes it for me, if so it is possibly a Qt bug but I think plugins should prefer delayed initialization of objects in any case.

**Comment by berquist** [comment]
That fixes it for me as well.

**Comment by cryos** [comment]
Thanks for verifying.
