### ISSUE TITLE
Please enable descriptions `Advanced molecular editor` and `Manage HPC jobs from the system tray` in the menu to be translatable

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#217]
`Advanced molecular editor`

![Avogadro2](https://user-images.githubusercontent.com/17465872/132784466-1cf9f19a-538b-41c4-8529-e4b78e2f2f5e.png)

`Manage HPC jobs from the system tray`

![MoleQueue](https://user-images.githubusercontent.com/17465872/132784476-0b6f94ca-a932-4faf-843b-9fdb2a138c64.png)

Avogadro2 Version 1.95.1
MoleQueue 0.9.0

**Comment by ovari** [comment]
@ghutchis do you know where the desktop entry file is for Avogadro2? Thank you

**Comment by ghutchis** [comment]
`./avogadro/icons/avogadro2.desktop`

**Comment by ovari** [comment]
Thank you @ghutchis
