### ISSUE TITLE
Where are the strings to translate MoleQueue?

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#218]
Where are the strings to translate MoleQueue? Are they in [Weblate](https://hosted.weblate.org/projects/avogadro/)?

![MoleQueue](https://user-images.githubusercontent.com/17465872/132785228-3b3e625e-a59c-4fb1-a07c-7777c428dd70.png)

Thank you

**Comment by ghutchis** [comment]
MoleQueue is a completely separate app: https://github.com/openchemistry/molequeue
