### ISSUE TITLE
Menu bar shows both `Fájl` and `File` which are the Hungarian and English spelling with no icons with the Hungarian options

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#267]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145 from https://github.com/OpenChemistry/avogadroapp/issues/207#issuecomment-1156982114

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
`File` menu shows twice, once in Hungarian and then later in English

**To Reproduce**
1. Set the locale to `Hungarian`
2. Open Avogadro
3. Menu bar shows `Fájl` and `File` in Hungarian and English respectively
4. Errors are shown in the Screenshots section below

Also the first `Fájl` incorrectly does not show icons next to the options in the list. The second `File` correctly shows the icons next to the options in the list.

**Expected behavior**
1. Menu bar to show `Fájl` with icons next to the options.
2. Menu bar does not show `File`

**Screenshots**
1. ![Fájl](https://user-images.githubusercontent.com/17465872/174023853-f2bb5bab-5264-40a6-8366-cc8ec40e75eb.png)
2. ![File](https://user-images.githubusercontent.com/17465872/174023897-75e9d196-9f0b-4ca4-a838-68c270575bed.png)

Thank you

**Comment by ghutchis** [comment]
Thanks for all the i18n bug reports. A few are easy and I'm pushing through fixes. This one will take a bit.

I can now test your Hungarian translation on my Mac as well - so it is a very helpful test of untranslated strings.

**Comment by ghutchis** [comment]
There was a bare string for "File" and "Open Recent" in `mainwindow.cpp` .. they're gone now.

I think there may be some slight differences showing up on Weblate before this is totally fixed.

**Comment by ovari** [comment]
Verified as fixed. Thank you

![image](https://user-images.githubusercontent.com/17465872/180174881-624cd7ef-96a2-4e5b-a4b2-b7277c413d8f.png)
