### ISSUE TITLE
Periodic Table: valence configuration, state of matter of most stable isotope, group name, melting/boiling points, half-life, Pauling scale of electronegativities

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#287]
![Periodic Table](https://user-images.githubusercontent.com/17465872/176978310-6abfda58-a36b-4a9c-861b-9a587ac1eb72.png)

For the selected element in the Periodic Table, please add other information, if appropriate, such as:
1. Valence configuration
[Periodic Table of the Elements.odt](https://github.com/OpenChemistry/avogadroapp/files/9032044/Periodic.Table.of.the.Elements.odt)
[Periodic Table of the Elements.pdf](https://github.com/OpenChemistry/avogadroapp/files/9032045/Periodic.Table.of.the.Elements.pdf)
https://chemed.chem.purdue.edu/genchem/topicreview/bp/ch6/quantum.html
2. State of matter for the most stable isotope, i.e. solid, liquid, gas, synthetically prepared
![image](https://user-images.githubusercontent.com/17465872/176978579-58109e05-d688-4810-81f3-17d6f9121072.png)
https://lawebloca.com/wp-content/uploads/2012/10/Periodic-Table-of-Element-09.jpg
3. Group, i.e. alkali metal, alkaline earth metal, transitional metal, other metal, non-metal, nonmetal, [noble gas/inert gas](https://pediaa.com/difference-between-inert-gases-and-noble-gases/)
4. Melting point
5. Boiling point
6. Half-life
7. Pauling scale of electronegativities
![Pauling scale of electronegativities](https://user-images.githubusercontent.com/17465872/176979436-e1c2f717-ca10-470e-936e-efecb1a16e88.png)

What do you think?

Thank you

**Comment by ghutchis** [comment]
Maybe? You should check out our friends [Kalzium](https://apps.kde.org/kalzium/) - Marcus actually worked on the Avogadro-Kalzium integration a while ago.

**Comment by ovari** [comment]
Should the `Extensions` menu have `Data Sheet`? Something which contains things like:
[Data Sheet.odt](https://github.com/OpenChemistry/avogadroapp/files/9032167/Data.Sheet.odt)
[Data Sheet.pdf](https://github.com/OpenChemistry/avogadroapp/files/9032168/Data.Sheet.pdf)
?

Should the `Period Table` option in Avogadro open Kalzium?
