### ISSUE TITLE
Error while reading file...

### ISSUE THREAD

**Issue by hluten** [OpenChemistry/avogadroapp#30]
OpenBabel error: conversion failed
when opening a .DAT output file from a GAMESS calculation (6,098 kB)
gamess.13-64.pgi.linux.blas.exe 64 bit windows version of GAMESS

I have been unable to load most output files for the calculations I am running.  These are geometric optimizations of medium sized molecules (18 non-H atoms) via DFT

**Comment by ghutchis** [comment]
Open Babel has never supported the GAMESS .DAT files. It can read the output (e.g., .log) but not the DAT files. If you have an issue with Open Babel, it has a separate GitHub issue page. http://github.com/openbabel/openbabel/issues

**Comment by ghutchis** [comment]
I'm closing this. I have no problems opening the output/log file from GAMESS and it's an Open Babel issue anyway.
