### ISSUE TITLE
`Discussion Forum`, `Avogadro Website`, `Report a bug`, `Suggest a Feature` do not work

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#313]
`Discussion Forum`, `Avogadro Website`, `Report a bug`, `Suggest a Feature` do not work with AppImage on Linux Mint 20.3 Cinnamon.

![image](https://user-images.githubusercontent.com/17465872/180180348-92bcb420-719b-4c4c-876c-23aa781043f0.png)

Thank you

**Comment by ovari** [comment]
Just downloaded now using link from https://github.com/OpenChemistry/avogadroapp/issues/277#issuecomment-1193332864 and does not work.

Should this issue be re-opened?

Thank you

**Comment by ghutchis** [comment]
If running `xdc-open` through a process doesn't work, there is no other known workaround. That was the proposed solution by probono in the link you posted.

**Comment by ghutchis** [comment]
Let me be clear, if a bug isn't solve, you can re-open. I'm just not sure how one would fix it.

**Comment by ovari** [comment]
Perhaps this issue can be closed once the new flatpak edition is released and checked to work. What do you think?

**Comment by ovari** [comment]
Links work with update flatpak.

`Report a bug`, and `Suggest a Feature` opens [avogadrolibs](https://github.com/OpenChemistry/avogadrolibs/). Is that correct or should it open [avogadroapp](https://github.com/OpenChemistry/avogadroapp/)?

If this is correct, please close this issue.

Thank you

**Comment by ghutchis** [comment]
The `avogadroapp` repo has much less code .. most bugs are likely to be over there and we transfer as needed.
