### ISSUE TITLE
Flatpak published to Flathub relies on EOL 21.08 Freedesktop runtime

### ISSUE THREAD

**Issue by bapride11** [OpenChemistry/avogadroapp#415]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.8

**Desktop version: (please complete the following information):**
 - OS: Linux
 - Version: Fedora 38, Flatpak from Flathub
 - Compiler: N/A

**Describe the bug**
The current Flatpak published to Flathub relies on the 21.08 Freedesktop runtime which is now EOL.  Perhaps try a quick build against a more recent Flatpak runtime? Reporting against avogadroapp because it's just an app packaging issue (no functional issue).

**Comment by ghutchis** [comment]
@kevinsmia1939 - how hard would this be to do?

**Comment by kevinsmia1939** [comment]
Should not be hard. Will update soon.

**Comment by ghutchis** [comment]
Can I close this? Seems like the PR was successful.

**Comment by kevinsmia1939** [comment]
I think we can close this.
