### ISSUE TITLE
Use new CMake Drag N Drop installer on Mac

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/avogadroapp#42]
This offers the fancier looking image, the Tomviz project is using it, can all be done in CPack/CMake.

**Comment by ghutchis** [comment]
I'd be happy to provide the icons from the Mac v1 installers.

**Comment by ghutchis** [comment]
![composed-dmg](https://cloud.githubusercontent.com/assets/41128/21054866/4b0d2be2-bdfd-11e6-9035-8e714dd6c93b.png)
![diskimage](https://cloud.githubusercontent.com/assets/41128/21054885/5a374d32-bdfd-11e6-8a58-dd3454476384.png)
