### ISSUE TITLE
Documentation error in the website to Build Source Code

### ISSUE THREAD

**Issue by m-rahul-karthik** [OpenChemistry/avogadroapp#441]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (e.g. 1.90.0-316-g6d14770)
 - Qt: (e.g., 5.9.5)

**Desktop version: (please complete the following information):**
 - OS: Windows 11
 - Version 22H2
 - Compiler (if you built from source)

**Describe the bug**
The hyperlink is expected go to a working page regarding the architecture dependent downloads , but it is redirecting to a 404 page not found error . 

**To Reproduce**
1. Go to README.md
2. Scroll down to the Installing subsection 
3. Click on the hyperlink of [building Open Chemistry](https://two.avogadro.cc/install/build.html) .
4. Scroll down to Debian-based Distribution or Ubuntu . 
5. Click on the hyperlink of [architecture](https://github.com/Kitware/CMake/releases/download/v3.26.5/) . 
6. See error

**Expected behavior**
The hyperlink is expected go to a working page regarding the architecture dependent downloads.

**Screenshots**
![Error_documentation](https://github.com/OpenChemistry/avogadroapp/assets/137385381/50ca6839-71be-4b13-bca9-1aa9f950c830)

**Additional context**

**Comment by ghutchis** [comment]
This bug has been fixed in https://github.com/avogadro/two.avogadro.cc
