### ISSUE TITLE
In mobile view there is no responsiveness which have to be improved.

### ISSUE THREAD

**Issue by pankaj-2503** [OpenChemistry/avogadroapp#460]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish Avogadro calculated XYQ moments to render with ..
All the cards present are not mobile responsive there content must have to be in center which is flowing in mobile view as seen in screenshot below.

![image](https://github.com/OpenChemistry/avogadroapp/assets/90036864/24431c0a-f4e6-4f6e-a16e-b377d07657a4)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please be detailed. How might this feature work (e.g., first a window would open and you'd click to …)
It should be mobile responsive by adding some css.
**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
This is an issue for the website: https://github.com/avogadro/two.avogadro.cc - not here

I'm not sure how critical those particular cards are for accessing on a phone, but I'm happy to discuss on the forum as indicated above.
