### ISSUE TITLE
Web component packaging on Windows

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/avogadroapp#48]
The web components introduce a perceived runtime dependency on BluetoothApis.dll, which cannot be resolved, and breaks packaging for the Windows platform. This looks like an issue with the Qt5 web component DLLs, but will need further investigation. Short term it may be necessary to disable any plugins requiring the web components.

**Comment by ghutchis** [comment]
There's an issue with the web engine packaging on Mac too (i.e., everything crashes because the helper isn't found)

http://doc.qt.io/qt-5/qtwebengine-deploying.html

Frankly Qt WebEngine is pretty brittle, IMHO.

**Comment by ghutchis** [comment]
For now, we've resolved this using #171 and rendering PNG.
