### ISSUE TITLE
VERSION_IS_RELEASE cmake variable

### ISSUE THREAD

**Issue by light2yellow** [OpenChemistry/avogadroapp#53]
In `DetermineVersion.cmake`, line 53:
```cmake
if ("${major}.${minor}.${patch}" EQUAL "${full}")
```
shouldn't this be `STREQUAL` instead? `VERSION_IS_RELEASE` is always `TRUE`, i. e. when this is not the tag annotated release which is not the expected behaviour.

**Comment by cryos** [comment]
I will take a look, I have never noticed any problems with this functionality, are you seeing issues somewhere or questioning the CMake from reading it? I didn't write any of that code, it is used in quite a few repositories.

**Comment by light2yellow** [comment]
@cryos just from reading the CMake. I want to adapt this for our own project (ckb-next) and make it simple for the user to report bugs. When it's not the release version, the version-related define instruction inside the program is the last release version plus the git commit hash, when it's release - it's just 3 numbers. Just like here I suppose. So let's think about it: here we compare two strings, so this is quite logical to do this using STREQUAL, isn't it? The "full" variable gets populated with git commit hash after the release version if this is being built from specific unannotated commit. Otherwise it contains those 3 numbers set manually at the beginning.

From CMake docs, `EQUAL`:
> True if the given string or variable’s value is a valid number and equal to that on the right.

and `STREQUAL`:
> True if the given string or variable’s value is lexicographically equal to the string or variable on the right.

~~If I'm not mistaken quotation marks say that both are strings, so we are comparing strings. `EQUAL` would probably work correct because it says "if the given string or variable’s value is a valid number" so when~~
Actually while writing this I understood why it will work. Because `EQUAL` will check whether both strings are legit numbers when "full" is populated with commit postfix it is not a number so the condition is false. And if the second string is a legit number, then both numbers ~~are probably~~ should be compared component-wise (because it **might** happen that someone forgets to manually bump numbers in cmake and make an annotated tag) which means it then requires `VERSION_EQUAL`.

To sup up, I guess `STREQUAL` would be the best solution.

**Comment by cryos** [comment]
I just double checked and we are using this version in a number of places, in CMake everything is a string, and then different commands have CMake evaluate them as strings, numbers, booleans, etc. In practice this code has worked well for us in a number of places, if it is a release I think numeric or string comparison would work, but it would always fail if the version introduced non-numeric characters - desirable with our versioning schemes.

**Comment by light2yellow** [comment]
Yes, exactly what I'm talking about. Although there's still an option of mismatching between tags and manual cmake versioning this is working in 99% cases. Thanks for clearing this out. Btw, huge props to the guys who wrote the enormous openchemistry CMake stack, a lot to learn from.

**Comment by cryos** [comment]
I am glad it has been useful as a learning tool for others, we are hoping to update it in a number of places - it is even easier to do some of the things we were doing more manually in CMake 3.3+.
