### ISSUE TITLE
Support for batch-generating Gaussian inputs from a multi-molecule file

### ISSUE THREAD

**Issue by Diazonium** [OpenChemistry/avogadroapp#56]
It would be very useful to be able to batch-generate inputs for Gaussian, when you have a multi-molecule file loaded, for example when you want to do conformational analysis.

**Comment by ghutchis** [comment]
Agreed. At the moment, the holdup is on handling multi-molecule files.

**Comment by ghutchis** [comment]
This issue was moved to OpenChemistry/avogadrolibs#177
