### ISSUE TITLE
Crash when measuring more than two atoms

### ISSUE THREAD

**Issue by jevandezande** [OpenChemistry/avogadroapp#61]
Avogadro2 crashes when I attempt to measure more than two atoms. The first two atoms can be selected and the distance between them appears; however, upon selecting the third atom the program crashes with the following output:

```
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
zsh: segmentation fault (core dumped)  ./avogadro2 ~/tmp/orca/IrCl6/geom.xyz
```

This happens no matter what atoms I try to measure: on symmetric and asymmetric molecules, when I load a file from the command line as while as within the app using `open`, and when I measure bonded or non-bonded distances.

Here is the full output I get when running avogadro:
```
Extension plugins dynamically found... 24
OBProcess::executeObabel: Running "obabel" "-L formats read"
OBProcess::executeObabel: Running "obabel" "-L formats write"
OBProcess::executeObabel: Running "obabel" "-L forcefields"
OBProcess::executeObabel: Running "obabel" "-V"
"obabel"  found:  "obabel: Open Babel 2.3.2 -- Oct 24 2016 -- 09:36:56"
Checking for generator scripts in "/home/vandezande/.local/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/share/ubuntu/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/local/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/workflows"
Checking for generator scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for file format scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/formatScripts"
SymmetryScene constructor
SymmetryScene::process
Missing origo or radius
"Navigator" added
"Editor" added
"Selection" added
"Manipulator" added
"BondCentric" added
"MeasureTool" added
"PlayerTool" added
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
zsh: segmentation fault (core dumped)  ~/progs/openchemistry-build/avogadroapp/bin/avogadro2 geom.xyz
```

**Comment by ghutchis** [comment]
What version are you using?

**Comment by jevandezande** [comment]
Sorry for the slow response, yesterday was a holiday here in Germany. I compiled from the Avogadro2 source on Ubuntu 17.04 using g++ 6.3.0, CMake 3.7.2, and Qt 5.7.1. I didn't notice any errors when compiling. I built from the Openchemistry supermodule following the instructions in the wiki.

Is there a way to run a testsuite on the program? I noticed mention of the `ENABLE_TESTS` flag in the wiki, but could not find directions on how to run tests.

**Comment by chicolucio** [comment]
Same problem here.

**Comment by ezavod** [comment]
Same here. Also crashes when holding left mouse button while moving (dragging) the mouse in drawing mode with similar error.
OS: openSUSE Tumbleweed 64bit
Avogadro2: 1.90.0-33-gd5e1f82
AvogadroLibs: 1.90.0-234-ga35df76
Qt: 5.10.0

**Comment by ghutchis** [comment]
This issue was moved to OpenChemistry/avogadrolibs#270
