### ISSUE TITLE
Optimize Geometry - "Error interpreting obabel MDL output"

### ISSUE THREAD

**Issue by 1ykos** [OpenChemistry/avogadroapp#62]
Freshly pulled from git and compiled without errors trying to optimize geometry produces the stated error: "Error interpreting obabel MDL output".
It seems the way in which obabel is invoked is wrong.
`OBProcess::executeObabel: Running "/home/usr/bin/openchemistry/prefix/bin/obabel" "-imol -omol --minimize --log --crit 1e-6 --ff GAFF --steps 2500 --rvdw 10 --rele 10 --freq 10"
MDL: "Open Babel 2.4.1 -- Aug 14 2017 -- 14:41:50\nUsage:\nobabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]\nTry  -H option for more information.\n"` 
the zlib linking issue in obabel (26) could also be the cause.

**Comment by cryos** [comment]
This works locally, checked and I am using the same version of obabel on Linux here. I wonder if it is related to that, or error checking if the optimization can't complete for some reason. If the forcefield plugin doesn't load it may then not recognize the option.

**Comment by ghutchis** [comment]
(bump)

**Comment by ghutchis** [comment]
@1ykos - if this is still a problem, please respond. It works for me, and I'd like to resolve old issues.

**Comment by ghutchis** [comment]
This issue was moved to OpenChemistry/avogadrolibs#203
