### ISSUE TITLE
won't open in fedora 27

### ISSUE THREAD

**Issue by murpholinox** [OpenChemistry/avogadroapp#63]
![captura de pantalla de 2017-12-14 11-21-11](https://user-images.githubusercontent.com/732802/34005674-4d575296-e0c1-11e7-9bfa-8e0942e672dc.png)

**Comment by sagitter** [comment]
If `avogadro2` comes from Fedora's repository, i confirm this error.
I will fix it soon.

**Comment by cryos** [comment]
Yeah that is a packaging issue, please let me know if you need us to make changes but that should be easy to fix by relinking/installing.

**Comment by sagitter** [comment]
@murpholinox 

`Avogadro2` is fixed on Fedora. Please, update your packages with:

`dnf update avogadro2 avogadro2-libs spglib --enablerepo=updates-testing`

and leave a feedback on the updates ticket: https://bodhi.fedoraproject.org/updates/FEDORA-2017-b7092f20fa

**Comment by ghutchis** [comment]
Thanks to @sagitter - I'm closing this bug - please see the updated package.
