### ISSUE TITLE
Provide a Linux build?

### ISSUE THREAD

**Issue by shrx** [OpenChemistry/avogadroapp#68]
Is it possible to provide a Linux build of Avogadro2 along with the Windows and macOS builds? Perhaps in the form of a .deb package?

**Comment by cryos** [comment]
This has been on my list for a while, I would like to offer a cross-distro binary. They are a pain to make, especially as several of our dependencies are quite new (relatively speaking). There are a few cross-distro packaging formats now, and so that may make things simpler.

**Comment by barrymoo** [comment]
Would a Singularity/Docker container be useful in this case?

**Comment by cryos** [comment]
Unless things have changes, Docker is awful when you need hardware accelerated rendering as we do. There is an NVIDIA CUDA container now, and I know they were working on something for rendering. It would be great to get at some point, the other complication with containers is access to your file system.

I remain open to suggestions, worst case (and we do this for ParaView, Tomviz, etc) is a tarball with binaries built on Debian stable for old glibc...

**Comment by fusion809** [comment]
This somewhat relates to cryos/avogadro#874 and https://discuss.avogadro.cc/t/appimage-builds/2739. AppImage seems like the format that will be adopted, with time.

**Comment by RizzerOnGitHub** [comment]
avogadro 1.91 is now available for Debian, https://packages.debian.org/unstable/avogadro
