### ISSUE TITLE
jsoncpp static library really needed by avogadroapp? 

### ISSUE THREAD

**Issue by gmrandazzo** [OpenChemistry/avogadroapp#70]
Dear Markus, Dear all,

i'm writing regarding this bug request. https://bugs.gentoo.org/649860 

i realised that avogadroapp need the static library of jsoncpp which is required by avogadrolibs

Here the error code:

```
CMake Error at /usr/lib64/cmake/avogadrolibs/AvogadroLibsTargets.cmake:214 (message):
  The imported target "jsoncpp" references the file

     "/usr/lib64/libjsoncpp.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/avogadrolibs/AvogadroLibsTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/avogadrolibs/AvogadroLibsConfig.cmake:22 (include)
  avogadro/CMakeLists.txt:1 (find_package)

```

 

So, i wrote a jsoncpp revision ebuild to solve this problem. However the ebuild will not be accepted.  https://bugs.gentoo.org/649860

How to fix this problem?
Is there any particular reason to use the static library instead of the dynamic one?

Thanks.
Best regards
GMR

**Comment by cryos** [comment]
It is just a tiny library, no particular reason why it has to be the static one. I know we haven't updated it in a while, and I am not sure if we have the code to find and link to an external jsoncpp. I don't have time right now, but will see if I can take a look at improving this. I was once a Gentoo developer, and fully agree with the need to be able to use system packages and dynamically linked libraries.

**Comment by ghutchis** [comment]
@cryos - might be worth considering using rapidjson:
https://github.com/Tencent/rapidjson/

Open Babel just switched and it's header-only. RDKit is also using it.
https://github.com/openbabel/openbabel/pull/1776

**Comment by cryos** [comment]
@ghutchis I actually really want to switch to [JSON for Modern C++](https://github.com/nlohmann/json) (and have a little experimental code). Its integration with C++ API is much nicer, and it is also header only. JsonCpp was a good choice at the time, but some of the new header only approaches look better.

**Comment by ghutchis** [comment]
We've switched, so I'm closing this one.
