### ISSUE TITLE
Segmentation Fault on Arch Linux and Ubuntu 14.04, and general slow performance while drawing on Arch and Fedora

### ISSUE THREAD

**Issue by barrymoo** [OpenChemistry/avogadroapp#8]
I am currently working on setting up a development environment for avogadroapp. I compiled the code on an up to date Arch Linux system, however I am running into:
<ol>
<li>A segmentation fault (specific keystrokes necessary)</li>
<li>General slow performance</li>
</ol>
For 1., I open the app, go to <code>Draw</code> mode, then attempt to draw an atom, and get a segmentation fault. I don't get the fault if I first open up a structure, then go to <code>Draw</code>, and attempt to draw an atom. I ran <code>gdb</code> to back-trace the segmentation fault. The relevant output:
<pre>
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6c25730 in Avogadro::QtGui::RWMolecule::addAtom (this=0x0, num=6 '\006') at /home/barrymoo/src/openchemistry/avogadrolibs/avogadro/qtgui/rwmolecule.cpp:119
119	  Index atomId = static_cast<Index>(m_molecule.m_atomicNumbers.size());
(gdb) bt
#0  0x00007ffff6c25730 in Avogadro::QtGui::RWMolecule::addAtom (this=0x0, num=6 '\006') at /home/barrymoo/src/openchemistry/avogadrolibs/avogadro/qtgui/rwmolecule.cpp:119
#1  0x00007ffff78a612d in Avogadro::QtPlugins::Editor::emptyLeftClick (this=0xa0eb20, e=0x7fffffffda20)
    at /home/barrymoo/src/openchemistry/avogadrolibs/avogadro/qtplugins/editor/editor.cpp:236
#2  0x00007ffff78a59c2 in Avogadro::QtPlugins::Editor::mousePressEvent (this=0xa0eb20, e=0x7fffffffda20)
    at /home/barrymoo/src/openchemistry/avogadrolibs/avogadro/qtplugins/editor/editor.cpp:103
#3  0x00007ffff7bd3127 in Avogadro::QtOpenGL::GLWidget::mousePressEvent (this=0x7173f0, e=0x7fffffffda20)
    at /home/barrymoo/src/openchemistry/avogadrolibs/avogadro/qtopengl/glwidget.cpp:267
#4  0x00007ffff567a4bf in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff5636acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff563c7d3 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff4d50dbb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff563b2ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff56924d0 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff5694643 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff5636acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff563bf10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff4d50dbb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff507e752 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#15 0x00007ffff5080305 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#16 0x00007ffff50651ef in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#17 0x00007fffe25d41b0 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#18 0x00007fffe97d49fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007fffe97d4ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007fffe97d4d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff4da91b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007ffff4d4e852 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff4d5622c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#24 0x00000000004277d8 in main (argc=1, argv=0x7fffffffe4f8) at /home/barrymoo/src/openchemistry/avogadroapp/avogadro/avogadro.cpp:99
</pre>
With the help of some colleagues, I can reproduce the segmentation fault on Ubuntu (but not Fedora). Unfortunately, I don't know where to go from here.

For 2., On Arch Linux and Fedora, when drawing atoms, the performance is quite poor (on Ubuntu the GLWidget, which I believe is the name for the display, won't appear and I don't know the performance). It can take a few seconds to press and drag an atom across the screen (A different Fedora machine with a 1GB dedicated graphics card runs more smoothly). It may be that 1. and 2. are related, however the former problem causes a segmentation fault. It may just be the system specs are too poor to adequately use <code>Draw</code> mode, but freely rotating a molecule in "Navigate" works flawlessly. Note, that I have installed the pre-built package on my Windows 8 machine and the program runs flawlessly. All of the packages have been installed using the package managers from the Linux distribution (<code>pacman</code>, <code>yum</code>, and <code>apt-get</code>. I built against the downloaded version of Qt 5.4 from the website with the same segmentation fault (the only change is the location of libQt5Widget.so). I would gladly supply additional information and would help testing the software. Thank you.

**Comment by cryos** [comment]
Can you pull the latest master? The segfault looks like a bug I introduced temporarily - you can see this is null (0x0), and that would explain the behavior you saw. This should be fixed now, but I can take a look if you are still seeing it. I develop on Arch, and so things should work well there in general (I also develop on Mac OS X, and do some testing on Windows 7).

There is an odd lag I am looking into for drawing, I am aware of it, and it seems to mainly affect machines where the GPU is only drawing a set number of frames per second (VSYNC). I will try to get this fixed up soon, it effectively requires suppressing some of the renders that are not necessary. Thanks for reporting your issues - let me know if updating to master fixes things up for you.

**Comment by barrymoo** [comment]
I pulled the latest master and rebuilt, the described segmentation fault is no longer present. The drawing lag actually seems slightly better too. The app was unusable previously, but now I can use the drawing tool. I will build it on my home machine (more RAM, better video card) and see if the performance is better there too (and let you know, for reference). Thanks!

**Comment by cryos** [comment]
I develop on an Ubuntu laptop too, with onboard Intel i7 graphics and can render millions of atoms. Any lag I suspect is an artifact of signal/slot explosion when editing -- too many redraw requests on machines that are VSYNC locked. There should be no real performance issues when looking at systems with small numbers of atoms.

**Comment by cryos** [comment]
Closing this as it seems to be fixed up, please reopen if that is not the case.
