### ISSUE TITLE
Executes an obabel command that is not recognized by Open Babel 3 (built from latest git commit)

### ISSUE THREAD

**Issue by fusion809** [OpenChemistry/avogadroapp#81]
Hi,

I packaged the OpenChemistry packages needed to build this application from their respective latest master git commit, along with this application itself, using the openSUSE Build Service. Avogadro 2 launches fine, but there's an issue with running obabel in it to optimize geometry. I started Avogadro 2 from the command-line so I could see the precise error messages and commands it is executing, this is what I saw when trying to optimize the geometry of a molecule:

```bash
OBProcess::executeObabel: Running "obabel" "-imol -omol --minimize --log --crit 1e-6 --ff  --steps 10000 --rvdw 10 --rele 10 --freq 10"
MDL: "Open Babel 2.4.90 -- May 28 2018 -- 20:57\nUsage:\nobabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]\nTry  -H option for more information.\n"
```

seems like the command is not found. Open Babel must be working somewhat given that I managed to open a SDF file, which I think requires the Open Babel backend to work. I tried a few example Open Babel 3 commands, however, and they all returned errors. Like when I ran the example command:

```bash
obabel -:"O=C(O)c1ccccc1OC(=O)C aspirin" -:"Oc1ccccc1C(=O)O salicylic acid" -ofpt
```

(per [the docs for 2.3.1](https://openbabel.org/docs/dev/Command-line_tools/babel.html), not sure if Open Babel 2 and 3 use the same syntax, however)

I received the output:

```bash
obabel: cannot write output format!
Open Babel 2.4.90 -- May 28 2018 -- 20:57
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.
```

If you want to look at the files I used to build Open Babel 3, [here](https://build.opensuse.org/package/show/home:fusion809/openbabel3) they are. If you want to see the build log click the "Succeeded text" next to the "openSUSE Tumbleweed" build target on the right side bar. Here's a screenshot showing exactly what I mean for the Avogadro 2 libraries package:

![screenshot_ opensuse-tumbleweed _20180711_112839](https://user-images.githubusercontent.com/4717341/42545964-793f2df6-84aa-11e8-958a-1b1d6dacc6dc.png)

. Avogadro 2 (i.e. avogadroapp) is [here](https://build.opensuse.org/package/show/home:fusion809/avogadro2). The libraries (avogadrolibs) are [here](https://build.opensuse.org/package/show/home:fusion809/avogadro2-libs). MoleQueue is packaged [here](https://build.opensuse.org/package/show/home:fusion809/molequeue). spglib is [here](https://build.opensuse.org/package/show/home:fusion809/spglib). I tried running an strace on the aspirin obabel command above, here is the output:

[obabel.log](https://github.com/OpenChemistry/avogadroapp/files/2182653/obabel.log)

Here is strace output for opening a SDF file with Avogadro 2 and trying to optimize the geometry:

[strace.log](https://github.com/OpenChemistry/avogadroapp/files/2182657/strace.log)

I really want this Avogadro 2 build to work to its fullest potential so please, if there's something you need to know in order to help fix this ask. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I've also tried editing avogadro2-libs, removing all patches and adjusting the spec file so the build occurs properly (as it changes the contents of the packages), and I get the same obabel issues. 

I'm wondering whether this might belong at discuss.avogadro.cc instead. As it involves an unofficial build of OpenChemistry.

**Comment by ghutchis** [comment]
Thanks, it's definitely better to handle a support request like this on the discussion forum.
