### ISSUE TITLE
Build error on openSUSE Tumbleweed: expected (, got newline and text

### ISSUE THREAD

**Issue by fusion809** [OpenChemistry/avogadroapp#87]
Hi,

On my i586 openSUSE Tumbleweed openSUSE Build Service (OBS) build target I get the cmake error:

```bash
[  135s] -- Detecting CXX compiler ABI info
[  136s] -- Detecting CXX compiler ABI info - done
[  136s] -- Detecting CXX compile features
[  139s] -- Detecting CXX compile features - done
[  139s] -- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
[  139s] -- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
[  139s] -- Could NOT find Git (missing: GIT_EXECUTABLE) 
[  139s] -- Could not use git to determine source version, using version 1.90.0
[  139s] -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
[  139s] -- Found Doxygen: /usr/bin/doxygen (found version "1.8.14") found components:  doxygen missing components:  dot
[  139s] CMake Error at cmake/AvogadroCPack.cmake:37:
[  139s]   Parse error.  Expected "(", got newline with text "
[  139s] 
[  139s]   ".
[  139s] Call Stack (most recent call first):
[  139s]   CMakeLists.txt:73 (include)
[  139s] 
[  139s] 
[  139s] -- Configuring incomplete, errors occurred!
[  139s] See also "/home/abuild/rpmbuild/BUILD/avogadroapp-b1838d884908acfbcc2a1f61259e8bea78be811e/build/CMakeFiles/CMakeOutput.log".
[  139s] error: Bad exit status from /var/tmp/rpm-tmp.MluVGZ (%build)
[  139s] 
```

(ignore the `[139s]`, it pertains to the build time in the OBS). The cmake command used is:

```bash
cmake -DCMAKE_BUILD_TYPE:STRING=Release \ 
 -Wno-dev \ 
 -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \ 
 -DENABLE_RPATH:BOOL=ON \ 
 -DENABLE_TESTING:BOOL=OFF \ 
 -DAvogadroLibs_DIR:PATH=/usr/lib32 \ 
 -DBUILD_DOCUMENTATION:BOOL=ON .. 
```

This is an error I only have gotten with the latest git commit #407, b1838d8. Earlier commits built fine. Full log is [here](https://gist.github.com/b6e1fa656a5f1b777e00d73f2c16d1fe).

Thanks for your time and patience,
Brenton

**Comment by cryos** [comment]
We should add a buildbot, I hadn't spotted the missing parantheses when looking over the code.

**Comment by fusion809** [comment]
You've got me, I build bleeding-edge Avogadro 2 packages for openSUSE Tumbleweed from the latest git commits of the Avogadro 2 OpenChemistry (OC) repositories, as well as MoleQueue, spglib and libmsym dependencies. I even have checkers for new commits in my i3 status bar. For example, the AvoA, AvoL and MolQ in the top bar of this screenshot pertain to avogadroapp, avogadrolibs and molequeue repositories, respectively. 

![screenshot_ opensuse-tumbleweed _20180719_034506](https://user-images.githubusercontent.com/4717341/42898397-918a387a-8ab2-11e8-99c9-7c710dd1b246.png)

Granted, of course, I can't guarantee I'll be able to keep this up long-term, so yes a bot would likely come in handy one day.

**Comment by cryos** [comment]
I very much appreciate it, we just need it in the code review to highlight issues like this before anything is merged. It is in avogadrolibs, but not here yet. Thanks for doing this, even if it is short term.
