### ISSUE TITLE
Add ability to plot energy when a suitable multi-geometry XYZ file is loaded

### ISSUE THREAD

**Issue by Diazonium** [OpenChemistry/avogadroapp#91]
It would be great if Avogadro could, after opening an XYZ file with multiple geometries, use the energy embedded in the comment line to create an energy plot. (X axis for the geometry number, Y axis for energy)
Here is a mock-up of an XYZ file that should be handled:
2
  MP2/cc-pVTZ Energy: -2.0000000
C 0.0 0.0 0.0
O 1.0 1.0 1.0
2
  DFT Energy: -1.5
C 0.00 0.000 0.00000
O 1.000 1.0 1.0050
2
-1.005
C 0.00 0.000 0.00000
O 1.000 1.0 2.0050

This should cover most of the variation that is commonly encountered.

**Comment by Diazonium** [comment]
I can provide some C++ functions that can parse these type of files, if that would help.

**Comment by ghutchis** [comment]
This issue was moved to OpenChemistry/avogadrolibs#364
