### ISSUE TITLE
Wrong release number

### ISSUE THREAD

**Issue by sagitter** [OpenChemistry/avogadroapp#92]
**Avogadro version:**
 - Avogadro: 1.91.0
 - Qt: 5.10.1

**Desktop version:**
 - OS: Fedora
 - Version: 28
 - Compiler: 8.1.1

**Describe the bug**
`Avogrado2` 's window shows `1.90.0` as release number.

**Expected behavior**
`1.91.0` release number

**Screenshots**
![screenshot from 2018-08-24 23-16-06](https://user-images.githubusercontent.com/5006433/44608665-c98b2b80-a7f4-11e8-9e88-505542753aa5.png)

**Comment by ghutchis** [comment]
Thanks for the report -- Is the build directory old? I have some of the old version numbers cached in my CMakeCache.txt files and had to blow things away on my Mac.

**Comment by cryos** [comment]
This was an oversight on my part when cutting the release. Geoff through me off a little as he incremented the number quite a while ago in the avogadrolibs CMakeLists.txt, but not the app. I normally do both one after another right before tagging. Sorry, you can patch the CMakeLists.txt at the top level - that is where it will get it from in the release tarballs when there is no git history.

I can cut a bug fix release soon, there are a few small things I need to fix. If it is packaging I think a local patch would be simplest, now it is tagged I will make a new release to address this and other issues in the near future. Thanks for reporting.

**Comment by sagitter** [comment]
@ghutchis 

No; it's created _ex novo_ at every new compilation.

**Comment by ghutchis** [comment]
This is fixed in 1.92, 1.93, etc.
